### ISSUE TITLE
请教一下这个efi能在mac10.13具体哪个镜像版本正常工作

### ISSUE THREAD

**Issue by LHB6540** [srole-xiaoxian/ASUS-R414U-Clover#1]
这个efi能在mac10.13镜像具体哪个版本正常工作，bios有没有什么要特殊设置的，比如说关闭网卡等

**Comment by srole-xiaoxian** [comment]
13.6(17G65)，没有具体要求，可能声卡注入的id不同会出现问题的，需要自己尝试。

**Comment by srole-xiaoxian** [comment]
我电脑集显使用的是Intel HD 620 ，如果不同，可能需要你自己修改原版镜像的文件

**Comment by LHB6540** [comment]
> 我电脑集显使用的是Intel HD 620 ，如果不同，可能需要你自己修改原版镜像的文件

谢谢，已经尝试了，非常完美。声音，系统睡眠，核显都正常。另外请教一下，独显920MX是被屏蔽了吗

**Comment by srole-xiaoxian** [comment]
> > 我电脑集显使用的是Intel HD 620 ，如果不同，可能需要你自己修改原版镜像的文件
> 
> 谢谢，已经尝试了，非常完美。声音，系统睡眠，核显都正常。另外请教一下，独显920MX是被屏蔽了吗

这个需要安装对应的NVIDIA显卡驱动，网上有许多教程

**Comment by 118253070146** [comment]
请问您的意思是GeForce 920mx也是可以安装黑苹果的对吗？我是个小白，最近在寻找这方面的教程，电脑显卡就是920mx的，许多人都说不行。

**Comment by LHB6540** [comment]
> 请问您的意思是GeForce 920mx也是可以安装黑苹果的对吗？我是个小白，最近在寻找这方面的教程，电脑显卡就是920mx的，很多人都说不行。

我有问过其他人，得到的解答是，由于硬件的限制，920MX没有独立的输出，所以不能驱动

**Comment by srole-xiaoxian** [comment]
> 请问您的意思是GeForce 920mx也是可以安装黑苹果的对吗？我是个小白，最近在寻找这方面的教程，电脑显卡就是920mx的，许多人都说不行。
需要Intel HD 620显卡，版本号为13.6(17G65)，如果机器为ASUS-R414U（X414u）基本可以安装
ps：独显在该colover中是驱动不了的，需要自己爬楼解决
